# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.TimeField(default=datetime.datetime(2017, 2, 10, 12, 57, 16, 552000)),
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.TimeField(default=datetime.datetime(2017, 2, 10, 12, 57, 16, 552000)),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
